### ISSUE TITLE
Assignment 3 - Peer Review Groups #27

### ISSUE THREAD

**Issue by Anh-NguyetLe** [STAT547-UBC-2019-20/group_08_ADULT-INCOME#33]
1. Reproducibility of scripts
- The repository is overall well-organized. However, I notice that there is a separate R script for every plot/ regression. If the project is big, this is not a very good practice in my opinion because there will be a lot of scripts to be managed and to be knitted together. I suggest that the scripts be organized into Load, Process, Analyze and Knit. In each script, if you want to keep track of different sections, an useful tip is to write a comment as:
 #comment or title of the section ---- (At least 4 dash):  the 4 dashes signal a section and in R you can view these sections in a dynamic menu. 
- There are also two files for data processing. Which one are you using? Might need to clean this up. 
- The scripts run to completion as described in the README and produce the expected output. However, under README there is no command line for the knit file. The make file doesn't produce the final html because of the error "No rule to make target `scripts/data_processing2.R'"

2. Use of functions and vectorized code 
-  The scripts and functions are appropriately documented.
- There is no vectorized code. One could be used to plot the net_education_plot and net_work_hours_plot together since they are pretty similar with the variable being education and work hour.

**Comment by jimmyliu1326** [comment]
Hi Anh, 

Thanks for your feedbacks!

* I certainly agree that we should consider merging the EDA-plot-generating scripts into a single script. We aim to address this in milestone04
* We have now combined the `data_processing.R` script into a single file rather than having two separate files. This was updated in the milestone03 release
* We will consider adding vectorized code to make the code more concise, but since the efficiency isn't a huge issue for our scripts, this will be a low priority for us
