### ISSUE TITLE
app layout

### ISSUE THREAD

**Issue by HJMcSorley** [STAT547-UBC-2019-20/group_08_ADULT-INCOME#52]
👋 @jimmyliu1326 

For our layout I think our sketch is mostly achievable... we can make a left side-bar with dropdown and radio buttons to select variables and isolate components of them, then have the associated graph on the right of that. I'm not 100% sure about having a summary table adjacent to the 'demographic overview' div. Maybe we could do that with tabs? Like, first tab is an overview plot, second tab is a summary table?

I'm pretty slow with apps still, but I'll concentrate on it today and tomorrow.

**Comment by jimmyliu1326** [comment]
Hey, yah I agree that we can have a left side-bar to have all the accessory components. It might look slightly odd using tabs to separate out the graphs and the summary table though, since the summary table will only have two columns at most, meaning that there might be too much white space when we are only displaying the table?

Let me try to make the graph and table fit together, I think it is certainly possible :D Making dash app is quite tricky haha. I have been looking at ways to make the app prettier as well like importing CSS.

**Comment by jimmyliu1326** [comment]
Hey Hannah, so I have divided the app into three scripts as Firaz showed us in class:
* app.R: the main script for launching app and defining app layout
* dash_functions.R: the script to create plots
* dash_components.R: the script to create components like headers, dropdowns, graphs..etc.

So, if you managed to finish the analytic plots and the accompanying sliders/dropdowns, I have included an object called "empty" in the `app$layout` call in `app.R`. So all you have to do is replace the "empty" object with your plot object, your plot should appear in the app. For the dropdowns or sliders you make, I have included a random dropdown object called "place_holder" in the `bottom_sidebar` component in `dash_components'. So all you have to do is replace the "place_holder" object with your dccDropdown or dccSlider objects. If you made multiple dropdowns or sliders, just add a comma behind them as if you are specifying multiple elements in a list/vector.

Hope this made sense haha let me know if anything is confusing.

**Comment by HJMcSorley** [comment]
Amazing! Thanks Jimmy. I'm still working on it, and this is tremendously helpful.

**Comment by HJMcSorley** [comment]
Hey Jimmy, I am stuck on callbacks... currently, making selections in the dropdown menus for the analytics graph doesn't alter the plot. I'm not sure where the error is. If you're able to have a look at my PR and see where I went wrong, that would be awesome. Thank you!

**Comment by jimmyliu1326** [comment]
Ah, I think it is because in the bottom_sidebar component you used place_holder_x and place_holder_y as the dropdown bars. But in your callback you are referencing dropdown_x and dropdown_y, so nothing would change because the wrong dropdown components are included in the app layout. I would just delete the place_holder_x/_y, I only included the place_holder there in the first place is just to fill out the layout, but we can remove all those now :D

**Comment by HJMcSorley** [comment]
🤦‍♀ ahhhh okay! That was silly of me. Thank you!!
